[package]
name = "epiloglite"
version = "0.1.0"
authors = ["Jen Eleniel"]
description = "EpilogLite is a port of SQLite to Rust. Copyright (C) 2024 Tony M. Bishop"
license = "LGPL-3.0-only"
license-file = "LICENSE.md"
keywords = ["database", "sqlite", "relational", "sql"]
categories = ["database-implementations"]
edition = "2021"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
flagset = { version = "0.4.6", features = ["serde"] }
logos = "0.15.0"
