[workspace]
resolver = "3"
members = ["epiloglite", "epiloglite-core", "epiloglite-derive"]

[workspace.package]
version = "1.0.0-alpha.1"
edition = "2024"
license = "MIT or Apache 2.0"
keywords = [
  "database",
  "embedded",
  "graph",
  "relational",
  "sql",
  "sqlite",
  "vector"
]
categories = ["database-implementations"]

[workspace.dependencies]
async-trait = { version = "0.1" }
bincode = { version = "2.0.1", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
crc-adler = { version = "0.1.1" }
epiloglite-core = { path = "./epiloglite-core" }
epiloglite-derive = { path = "./epiloglite-derive" }
flagset = { version = "0.4.6", features = ["serde"] }
log = { version = "0.4" }
logos = { version = "0.15.0" }
num-traits = { version = "0.2.19", features = ["i128"] }
regex = { version = "1.11" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
strum = { version = "0.27.2", features = ["derive"] }
sysinfo = { version = "0.37.2", features = ["serde"] }
thiserror = { version = "2.0" }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.18.1", features = ["fast-rng", "serde", "v4"] }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "deny"
