name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Please provide a clear and concise bug report. Include steps to reproduce and expected vs actual behavior.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: To Reproduce
      placeholder: Steps to reproduce the behavior, e.g., 1. Do X 2. Do Y
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: Add any screenshots to help explain the problem.
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: OS, Browser, Version, Device info
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.
      required: false
name: Bug Report
description: File a bug report.
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: Please provide as much detail as possible. Attach logs, examples, and other files to this report.
  - type: textarea
    id: unexpected-behavior
    attributes:
      label: Unexpected Behavior
      description: What happened that you did not expect?
      placeholder: Describe what actually happened, including any error messages or unexpected results.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected the application to do.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide a detailed list of steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Application Version
      description: What version of the application are you running?
      placeholder: e.g., v1.2.3 or commit hash
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    id: about
    attributes:
      label: About the Application
      description: Please paste the output of the "About" dialog.
      placeholder: About information including build details
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Include any logs, screenshots, or other relevant information
      placeholder: Attach any relevant logs, screenshots, or additional context that might help diagnose the issue
