name: Feature request
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Please describe your feature request in detail. Fields marked optional may be left blank.

  - type: textarea
    id: problem_description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of the problem.
      required: false

  - type: textarea
    id: solution_description
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      placeholder: Any alternative solutions you've considered
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about your feature request.
      required: false
name: Feature Request
description: Request a new feature or an enhancement to an existing feature.
title: '[feat]: '
labels: ['feature', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a new feature! Please fill out this form as completely as possible.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like to see implemented
      placeholder: Provide a clear and detailed description of the feature you're requesting
    validations:
      required: true
  - type: textarea
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit from this feature?
      placeholder: e.g., developers, end users, administrators, specific user roles
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: Benefits
      description: How would this feature improve the application?
      placeholder: List the specific benefits and improvements this feature would bring
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: Do you have any suggestions on how this could be implemented?
      placeholder: Share any technical details, API suggestions, or implementation ideas
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered and why they might or might not work
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Are there any examples of this feature in other products?
      placeholder: Share links, screenshots, or descriptions of similar features in other applications
